[build]
command = "./install_flutter.sh && flutter build web"
publish = "build/web"

[context.production.environment]
PATH = "$PATH:/opt/buildhome/flutter/bin"

[[plugins]]
package = "@netlify/plugin-install-local"
package = "@netlify/plugin-flutter"

[build.environment]
PATH = "/opt/buildhome/flutter/bin:$PATH"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
